DO NOT MERGE try to debug a CI failure
FreeBSD CI jobs have been failing for the last week or so, because Cargo
fails with an error like the following.  See if installing the
ca_root_nss root certificate bundle can fix it.

```
error: failed to get `askama` as a dependency of package `ctest v0.5.0-beta.3 (/tmp/cirrus-ci-build/ctest)`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate OpenSSL verify result: unable to get local issuer certificate (20))
```

Issue #4952