linux: Restructure `netlink` to `src/new`
Move netlink types defined in UAPI to the `new` module. This resolves
the following build error on uclibc platforms:

    error[E0425]: cannot find value `NLMSG_MIN_TYPE` in the crate root
        --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libc-0.2.179/src/unix/linux_like/linux/mod.rs:1999:48
         |
    1999 | pub const NFNL_MSG_BATCH_BEGIN: c_int = crate::NLMSG_MIN_TYPE;
         |                                                ^^^^^^^^^^^^^^ not found in the crate root
         |
    note: found an item that was configured out
        --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libc-0.2.179/src/unix/linux_like/linux_l4re_shared.rs:1222:19
         |
    1200 |     if #[cfg(not(target_env = "uclibc"))] {
         |                 ----------------------- the item is gated here
    ...
    1222 |         pub const NLMSG_MIN_TYPE: c_int = 0x10;
         |                   ^^^^^^^^^^^^^^

Fixes: 2fe1d91f1822 ("Separate L4Re from Linux code and enable tests")

(backport <https://github.com/rust-lang/libc/pull/4915>)
(cherry picked from commit e0ed72dc03f1d71d0ad6a014f2ef35dee4fd584d)