apple: Disable most `mach` API on Apple mobile OSs
Backporting the apple-*OS CI fixes around c859fcc87e9a ("Use
cargo-apple-runner for testing iOS and tvOS") fails on this branch with
errors like:

      cargo:warning=/Applications/Xcode_26.6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator26.5.sdk/usr/include/mach/mach_vm.h:1:2: error: mach_vm.h unsupported.
      cargo:warning=    1 | #error mach_vm.h unsupported.
      cargo:warning=      |  ^
      cargo:warning=/Users/runner/work/libc/libc/target/aarch64-apple-ios-sim/debug/build/libc-test/334ed535de220e54/out/ctest_output.c:37154:29: error: use of undeclared identifier 'mach_vm_map'
      cargo:warning= 37154 |     return (ctest_void_func)mach_vm_map;
      cargo:warning=       |                             ^~~~~~~~~~~
      cargo:warning=2 errors generated.

The mach API has long been deprecated anyway, so disable remove it on
iOS, watchOS, visionOS, and tvOS.