musl: Add a patch for `basename` to the 1.1.x build
In Ubuntu 26.04, the musl build hits:

    In file included from /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-1eed7f417ef9e9ac/out/ctest_output.c:51:
    /musl-aarch64/include/string.h:97:7: error: conflicting types for 'basename'; have 'char *(void)'
       97 | char *basename();
          |       ^~~~~~~~
    In file included from /checkout/target/aarch64-unknown-linux-musl/debug/build/libc-test-1eed7f417ef9e9ac/out/ctest_output.c:19:
    /musl-aarch64/include/libgen.h:9:7: note: previous declaration of 'basename' with type 'char *(char *)'
        9 | char *basename(char *);
          |       ^~~~~~~~
    cc1: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics

I believe this may be due to a new error in recent versions of GCC,
though I have not actually gone through the effort to verify this. In
any case, musl received a patch in 1.2.5 that resolves the issue; apply
it to our 1.1.x build to keep it working.

Link: https://github.com/kraj/musl/commit/725e17ed6dff4d0cd22487bb64470881e86a92e7