ci: Add back `contents: write` to the release-plz job
Currently fails with:

    2026-10-02T09:35:36.159382Z ERROR failed to release package

    Caused by:
      0: failed to create tag `1.0.0-alpha.5`
      1: Response body:
         {
           "documentation_url": "https://docs.github.com/rest/git/tags#create-a-tag-object",
           "message": "Resource not accessible by integration",
           "status": "403"
         }
      2: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/rust-lang/libc/git/tags)
    Error: failed to release package