ctest: Disable warning C4746 on Windows
This seems to be enabled by default on aarch64. We get a number of
errors like:

    C:\a\libc\libc\target\aarch64-pc-windows-msvc\debug\build\libc-test-57e9ef381db637c1\out\ctest_output.c(2190) : error C2220: the following warning is treated as an error
    C:\a\libc\libc\target\aarch64-pc-windows-msvc\debug\build\libc-test-57e9ef381db637c1\out\ctest_output.c(2190) : warning C4746: volatile access of '<expression>' is subject to /volatile:<iso|ms> setting; consider using __iso_volatile_load/store intrinsic functions

Our volatile use in tests isn't contested so we can safely ignore it.

Link: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-c4746?view=msvc-170