Re-export c_void from std::os::raw
This avoid silly errors like:

```
error: mismatched types:
 expected `*mut libc::c_void`,
    found `*mut std::os::raw::c_void`
```

and should have no other effect since the two definitions were identical.